apiVersion: apps/v1
kind: Deployment
metadata:
  name: baseline-workload
  namespace: workloads
  labels:
    app.kubernetes.io/name: baseline-workload
    app.kubernetes.io/part-of: gitops-benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baseline-workload
  template:
    metadata:
      labels:
        app: baseline-workload
    spec:
      containers:
        - name: web
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
