apiVersion: v1
kind: Service
metadata:
  name: baseline-workload-svc
  namespace: workloads
  labels:
    app.kubernetes.io/name: baseline-workload
spec:
  type: ClusterIP
  selector:
    app: baseline-workload
  ports:
    - name: http
      port: 80
      targetPort: 80
